name: mqppep
owner: eschen42
description: MaxQuant Phosphoproteomic Enrichment Pipeline - Preprocessing and ANOVA
homepage_url: 'https://github.com/galaxyproteomics/tools-galaxyp/'
long_description: |
  Phosphoproteomic Enrichment Pipeline provides tools two tools for processing MaxQuant data for phosphoproteome-enriched samples.
 
  "MaxQuant Phosphopeptide Preprocessing" (mqppep_preproc) transforms the 'Phospho (STY)Sites.txt' output file that MaxQuant produces for for phosphoproteome-enriched samples to prepare it for ANOVA.

  "MaxQuant Phosphopeptide ANOVA" (mqppep_anova) performs ANOVA on the preprocessed data.

remote_repository_url: https://github.com/galaxyproteomics/tools-galaxyp/tree/master/tools/mqppep
type: unrestricted
categories:
- Proteomics

auto_tool_repositories:
  name_template: "{{ tool_id }}"
  description_template: "wrapper for {{tool_name}} module."

suite:
  name: "suite_mqppep"
  description: suite for preprocessing and ANOVA of MaxQuant results for phosphoproteomic enrichment
  long_description: Phosphoproteomic Enrichment Pipeline provides tools for preprocessing the 'Phospho (STY)Sites.txt' file produced by MaxQuant and for ANOVA analysis of the preprocessed data.

include:
  - .shed.yml
  - MaxQuantProcessingScript.R
  - PhosphoPeptide_Upstream_Kinase_Mapping.pl
  - macros.xml
  - mqppep_anova.R
  - mqppep_anova.xml
  - mqppep_anova_script.Rmd
  - mqppep_mrgfltr.py
  - mqppep_preproc.xml
  - repository_dependencies.xml
  - search_ppep.py 
  - workflow/ppenrich_suite_wf.ga
  - test-data/alpha_levels.tabular
  - test-data/pSTY_motifs.tabular
  - test-data/test_kinase_substrate.tabular
  - test-data/test_swissprot.fasta
  - test-data/test_input_for_anova.tabular
  - test-data/test_networkin.tabular
  - test-data/test_regulatory_sites.tabular
  - test-data/test_input_for_preproc.tabular
